using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using VRage;
using VRage.Collections;
using VRage.Game;
using VRage.Game.Components;
using VRage.Game.GUI.TextPanel;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ModAPI.Ingame.Utilities;
using VRage.Game.ObjectBuilders.Definitions;
using VRageMath;

namespace IngameScript
{
    partial class Program
    {
        public class BlockIndex
        {
            private static Dictionary<string, BlockType> largeSize;
            private static Dictionary<string, BlockType> smallSize;
            static BlockIndex() {
                Dictionary<char, Component.ComponentType> dialect = new Dictionary<char, Component.ComponentType>();
                dialect.Add('A', Component.ComponentType.BulletproofGlass);
                dialect.Add('B', Component.ComponentType.Computer);
                dialect.Add('C', Component.ComponentType.Construction);
                dialect.Add('D', Component.ComponentType.Detector);
                dialect.Add('E', Component.ComponentType.Display);
                dialect.Add('F', Component.ComponentType.Explosives);
                dialect.Add('G', Component.ComponentType.Girder);
                dialect.Add('H', Component.ComponentType.GravityGenerator);
                dialect.Add('I', Component.ComponentType.InteriorPlate);
                dialect.Add('J', Component.ComponentType.LargeTube);
                dialect.Add('K', Component.ComponentType.Medical);
                dialect.Add('L', Component.ComponentType.MetalGrid);
                dialect.Add('M', Component.ComponentType.Motor);
                dialect.Add('N', Component.ComponentType.PowerCell);
                dialect.Add('O', Component.ComponentType.RadioCommunication);
                dialect.Add('P', Component.ComponentType.Reactor);
                dialect.Add('Q', Component.ComponentType.SmallTube);
                dialect.Add('R', Component.ComponentType.SolarCell);
                dialect.Add('S', Component.ComponentType.SteelPlate);
                dialect.Add('T', Component.ComponentType.Superconductor);
                dialect.Add('U', Component.ComponentType.Thrust);
                dialect.Add('V', Component.ComponentType.ZoneChip);

                largeSize = new Dictionary<string, BlockType>();
                smallSize = new Dictionary<string, BlockType>();

                string[] initializer =
                {
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks.sbc
                    "CubeBlock/LargeRailStraight%LS12C8J4",
                    "DebugSphere1/DebugSphereLarge%LS10B20",
                    "DebugSphere2/DebugSphereLarge%LS10B20",
                    "DebugSphere3/DebugSphereLarge%LS10B20",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Armor.sbc
                    "CubeBlock/LargeBlockArmorBlock%LS25",
                    "CubeBlock/LargeBlockArmorSlope%LS13",
                    "CubeBlock/LargeBlockArmorCorner%LS4",
                    "CubeBlock/LargeBlockArmorCornerInv%LS21",
                    "CubeBlock/LargeRoundArmor_Slope%LS13",
                    "CubeBlock/LargeRoundArmor_Corner%LS4",
                    "CubeBlock/LargeRoundArmor_CornerInv%LS21",
                    "CubeBlock/LargeHeavyBlockArmorBlock%LS150L50",
                    "CubeBlock/LargeHeavyBlockArmorSlope%LS75L25",
                    "CubeBlock/LargeHeavyBlockArmorCorner%LS25L10",
                    "CubeBlock/LargeHeavyBlockArmorCornerInv%LS125L50",
                    "CubeBlock/SmallBlockArmorBlock%SS1",
                    "CubeBlock/SmallBlockArmorSlope%SS1",
                    "CubeBlock/SmallBlockArmorCorner%SS1",
                    "CubeBlock/SmallBlockArmorCornerInv%SS1",
                    "CubeBlock/SmallHeavyBlockArmorBlock%SS5L2",
                    "CubeBlock/SmallHeavyBlockArmorSlope%SS3L1",
                    "CubeBlock/SmallHeavyBlockArmorCorner%SS2L1",
                    "CubeBlock/SmallHeavyBlockArmorCornerInv%SS4L1",
                    "CubeBlock/LargeHalfArmorBlock%LS12",
                    "CubeBlock/LargeHeavyHalfArmorBlock%LS75L25",
                    "CubeBlock/LargeHalfSlopeArmorBlock%LS7",
                    "CubeBlock/LargeHeavyHalfSlopeArmorBlock%LS45L15",
                    "CubeBlock/HalfArmorBlock%SS1",
                    "CubeBlock/HeavyHalfArmorBlock%SS3L1",
                    "CubeBlock/HalfSlopeArmorBlock%SS1",
                    "CubeBlock/HeavyHalfSlopeArmorBlock%SS2L1",
                    "CubeBlock/LargeBlockArmorRoundSlope%LS13",
                    "CubeBlock/LargeBlockArmorRoundCorner%LS4",
                    "CubeBlock/LargeBlockArmorRoundCornerInv%LS21",
                    "CubeBlock/LargeHeavyBlockArmorRoundSlope%LS130L50",
                    "CubeBlock/LargeHeavyBlockArmorRoundCorner%LS125L40",
                    "CubeBlock/LargeHeavyBlockArmorRoundCornerInv%LS140L50",
                    "CubeBlock/SmallBlockArmorRoundSlope%SS1",
                    "CubeBlock/SmallBlockArmorRoundCorner%SS1",
                    "CubeBlock/SmallBlockArmorRoundCornerInv%SS1",
                    "CubeBlock/SmallHeavyBlockArmorRoundSlope%SS4L1",
                    "CubeBlock/SmallHeavyBlockArmorRoundCorner%SS4L1",
                    "CubeBlock/SmallHeavyBlockArmorRoundCornerInv%SS5L1",
                    "CubeBlock/LargeBlockArmorSlope2Base%LS19",
                    "CubeBlock/LargeBlockArmorSlope2Tip%LS7",
                    "CubeBlock/LargeBlockArmorCorner2Base%LS10",
                    "CubeBlock/LargeBlockArmorCorner2Tip%LS4",
                    "CubeBlock/LargeBlockArmorInvCorner2Base%LS22",
                    "CubeBlock/LargeBlockArmorInvCorner2Tip%LS16",
                    "CubeBlock/LargeHeavyBlockArmorSlope2Base%LS112L45",
                    "CubeBlock/LargeHeavyBlockArmorSlope2Tip%LS35L6",
                    "CubeBlock/LargeHeavyBlockArmorCorner2Base%LS55L15",
                    "CubeBlock/LargeHeavyBlockArmorCorner2Tip%LS19L6",
                    "CubeBlock/LargeHeavyBlockArmorInvCorner2Base%LS133L45",
                    "CubeBlock/LargeHeavyBlockArmorInvCorner2Tip%LS94L25",
                    "CubeBlock/SmallBlockArmorSlope2Base%SS1",
                    "CubeBlock/SmallBlockArmorSlope2Tip%SS1",
                    "CubeBlock/SmallBlockArmorCorner2Base%SS1",
                    "CubeBlock/SmallBlockArmorCorner2Tip%SS1",
                    "CubeBlock/SmallBlockArmorInvCorner2Base%SS1",
                    "CubeBlock/SmallBlockArmorInvCorner2Tip%SS1",
                    "CubeBlock/SmallHeavyBlockArmorSlope2Base%SS4L1",
                    "CubeBlock/SmallHeavyBlockArmorSlope2Tip%SS2L1",
                    "CubeBlock/SmallHeavyBlockArmorCorner2Base%SS3L1",
                    "CubeBlock/SmallHeavyBlockArmorCorner2Tip%SS2L1",
                    "CubeBlock/SmallHeavyBlockArmorInvCorner2Base%SS5L1",
                    "CubeBlock/SmallHeavyBlockArmorInvCorner2Tip%SS5L1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Armor_2.sbc
                    "CubeBlock/LargeBlockArmorCornerSquare%LS7",
                    "CubeBlock/SmallBlockArmorCornerSquare%SS1",
                    "CubeBlock/LargeBlockHeavyArmorCornerSquare%LS40L15",
                    "CubeBlock/SmallBlockHeavyArmorCornerSquare%SS2L1",
                    "CubeBlock/LargeBlockArmorCornerSquareInverted%LS19",
                    "CubeBlock/SmallBlockArmorCornerSquareInverted%SS1",
                    "CubeBlock/LargeBlockHeavyArmorCornerSquareInverted%LS112L40",
                    "CubeBlock/SmallBlockHeavyArmorCornerSquareInverted%SS4L1",
                    "CubeBlock/LargeBlockArmorHalfCorner%LS6",
                    "CubeBlock/SmallBlockArmorHalfCorner%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfCorner%LS35L12",
                    "CubeBlock/SmallBlockHeavyArmorHalfCorner%SS2L1",
                    "CubeBlock/LargeBlockArmorHalfSlopeCorner%LS3",
                    "CubeBlock/SmallBlockArmorHalfSlopeCorner%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfSlopeCorner%LS12L4",
                    "CubeBlock/SmallBlockHeavyArmorHalfSlopeCorner%SS2L1",
                    "CubeBlock/LargeBlockArmorHalfSlopeCornerInverted%LS23",
                    "CubeBlock/SmallBlockArmorHalfSlopeCornerInverted%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfSlopeCornerInverted%LS139L45",
                    "CubeBlock/SmallBlockHeavyArmorHalfSlopeCornerInverted%SS5L1",
                    "CubeBlock/LargeBlockArmorHalfSlopedCorner%LS11",
                    "CubeBlock/SmallBlockArmorHalfSlopedCorner%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfSlopedCorner%LS45L5",
                    "CubeBlock/SmallBlockHeavyArmorHalfSlopedCorner%SS3L1",
                    "CubeBlock/LargeBlockArmorHalfSlopedCornerBase%LS11",
                    "CubeBlock/SmallBlockArmorHalfSlopedCornerBase%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfSlopedCornerBase%LS45L15",
                    "CubeBlock/SmallBlockHeavyArmorHalfSlopedCornerBase%SS3L1",
                    "CubeBlock/LargeBlockArmorHalfSlopeInverted%LS22",
                    "CubeBlock/SmallBlockArmorHalfSlopeInverted%SS1",
                    "CubeBlock/LargeBlockHeavyArmorHalfSlopeInverted%LS133L45",
                    "CubeBlock/SmallBlockHeavyArmorHalfSlopeInverted%SS5L1",
                    "CubeBlock/LargeBlockArmorSlopedCorner%LS13",
                    "CubeBlock/SmallBlockArmorSlopedCorner%SS1",
                    "CubeBlock/LargeBlockHeavyArmorSlopedCorner%LS75L25",
                    "CubeBlock/SmallBlockHeavyArmorSlopedCorner%SS3L1",
                    "CubeBlock/LargeBlockArmorSlopedCornerBase%LS20",
                    "CubeBlock/SmallBlockArmorSlopedCornerBase%SS1",
                    "CubeBlock/LargeBlockHeavyArmorSlopedCornerBase%LS127L40",
                    "CubeBlock/SmallBlockHeavyArmorSlopedCornerBase%SS5L1",
                    "CubeBlock/LargeBlockArmorSlopedCornerTip%LS5",
                    "CubeBlock/SmallBlockArmorSlopedCornerTip%SS1",
                    "CubeBlock/LargeBlockHeavyArmorSlopedCornerTip%LS23L6",
                    "CubeBlock/SmallBlockHeavyArmorSlopedCornerTip%SS2L1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Automation.sbc
                    "MyProgrammableBlock/SmallProgrammableBlock%SS2C2J2M1E1B2",
                    "MyObjectBuilder_Projector/LargeProjector%LS21C4J2M1B2",
                    "MyObjectBuilder_Projector/SmallProjector%SS2C2J2M1B2",
                    "SensorBlock/SmallBlockSensor%SI5C5B6O4D6S2",
                    "SensorBlock/LargeBlockSensor%LI5C5B6O4D6S2",
                    "TargetDummyBlock/TargetDummy%LS15Q10M2B4E1",
                    "SoundBlock/SmallBlockSoundBlock%SI4C6B3",
                    "SoundBlock/LargeBlockSoundBlock%LI4C6B3",
                    "ButtonPanel/ButtonPanelLarge%LI10C20B20",
                    "ButtonPanel/ButtonPanelSmall%SI2C2B1",
                    "TimerBlock/TimerBlockLarge%LI6C30B5",
                    "TimerBlock/TimerBlockSmall%SI2C3B1",
                    "MyProgrammableBlock/LargeProgrammableBlock%LS21C4J2M1E1B2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Communications.sbc
                    "RadioAntenna/LargeBlockRadioAntenna%LS80J40Q60C30B8O40",
                    "Beacon/LargeBlockBeacon%LS80C30J20B10O40",
                    "Beacon/SmallBlockBeacon%SS2C1Q1B1O4",
                    "RadioAntenna/SmallBlockRadioAntenna%SS1Q1C2B1O4",
                    "RemoteControl/LargeBlockRemoteControl%LI10C10M1B15",
                    "RemoteControl/SmallBlockRemoteControl%SI2C1M1B1",
                    "LaserAntenna/LargeBlockLaserAntenna%LS50C40M16D30O20T100B50A4",
                    "LaserAntenna/SmallBlockLaserAntenna%SS10Q10C10M5O5T10B30A2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Control.sbc
                    "TerminalBlock/ControlPanel%LS1C1B1E1",
                    "TerminalBlock/SmallControlPanel%SS1C1B1E1",
                    "Cockpit/LargeBlockCockpit%LI20C20M2B100E10",
                    "Cockpit/LargeBlockCockpitSeat%LS30C20M1E8B100A60",
                    "Cockpit/SmallBlockCockpit%SS10C10M1E5B15A30",
                    "Cockpit/DBSmallBlockFighterCockpit%SC20M1S20L10I15E4B20A40",
                    "Cockpit/CockpitOpen%LI20C20M2B100E4",
                    "Cockpit/RoverCockpit%SI30C25M2B20E4",
                    "Gyro/LargeBlockGyro%LS600C40J4L50M4B5",
                    "Gyro/SmallBlockGyro%SS25C5J1M2B3",
                    "Cockpit/OpenCockpitSmall%SI20C20M1B15E2",
                    "Cockpit/OpenCockpitLarge%LI30C30M2B100E6",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_DecorativePack.sbc
                    "Cockpit/LargeBlockDesk%LI30C30",
                    "Cockpit/LargeBlockDeskCorner%LI20C20",
                    "CubeBlock/LargeBlockDeskChairless%LI30C30",
                    "CubeBlock/LargeBlockDeskChairlessCorner%LI20C20",
                    "Kitchen/LargeBlockKitchen%LI20C30J6M6A4",
                    "CryoChamber/LargeBlockBed%LI30C30Q8A10",
                    "CargoContainer/LargeBlockLockerRoom%LI30C30E4A10",
                    "CargoContainer/LargeBlockLockerRoomCorner%LI25C30E4A10",
                    "Planter/LargeBlockPlanters%LI10C20Q8A8",
                    "Cockpit/LargeBlockCouch%LI30C30",
                    "Cockpit/LargeBlockCouchCorner%LI35C35",
                    "CargoContainer/LargeBlockLockers%LI20C20E3B2",
                    "Cockpit/LargeBlockBathroomOpen%LI30C30Q8M4J2",
                    "Cockpit/LargeBlockBathroom%LI30C40Q8M4J2",
                    "Cockpit/LargeBlockToilet%LI10C15Q2M2J1",
                    "Projector/LargeBlockConsole%LI20C30B8E10",
                    "Cockpit/SmallBlockCockpitIndustrial%SS10C20L10M2E6B20A60Q10",
                    "Cockpit/LargeBlockCockpitIndustrial%LS20C30L15M2E10B60A80Q10",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_DecorativePack2.sbc
                    "VendingMachine/FoodDispenser%LI20C10M4E10B10",
                    "Jukebox/Jukebox%LI15C10B4E4",
                    "LCDPanelsBlock/LabEquipment%LI15C15M1A4",
                    "CubeBlock/Shower%LI20C20Q12A8",
                    "CubeBlock/WindowWall%LS8C10A10",
                    "CubeBlock/WindowWallLeft%LS10C10A8",
                    "CubeBlock/WindowWallRight%LS10C10A8",
                    "LCDPanelsBlock/MedicalStation%LI15C15M2K1E2",
                    "TextPanel/TransparentLCDLarge%LC8B6E10A10",
                    "TextPanel/TransparentLCDSmall%SC4B4E3A1",
                    "CubeBlock/Catwalk%LC16G4Q20",
                    "CubeBlock/CatwalkCorner%LC24G4Q32",
                    "CubeBlock/CatwalkStraight%LC24G4Q32",
                    "CubeBlock/CatwalkWall%LC20G4Q26",
                    "CubeBlock/CatwalkRailingEnd%LC28G4Q38",
                    "CubeBlock/CatwalkRailingHalfRight%LC28G4Q36",
                    "CubeBlock/CatwalkRailingHalfLeft%LC28G4Q36",
                    "CubeBlock/GratedStairs%LC22Q12I16",
                    "CubeBlock/GratedHalfStairs%LC20Q6I8",
                    "CubeBlock/GratedHalfStairsMirrored%LC20Q6I8",
                    "CubeBlock/RailingStraight%LC8Q6",
                    "CubeBlock/RailingDouble%LC16Q12",
                    "CubeBlock/RailingCorner%LC16Q12",
                    "CubeBlock/RailingDiagonal%LC12Q9",
                    "CubeBlock/RailingHalfRight%LC8Q4",
                    "CubeBlock/RailingHalfLeft%LC8Q4",
                    "ReflectorLight/RotatingLightLarge%LC3M1",
                    "ReflectorLight/RotatingLightSmall%SC3M1",
                    "CubeBlock/Freight1%LI6C8",
                    "CubeBlock/Freight2%LI12C16",
                    "CubeBlock/Freight3%LI18C24",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Doors.sbc
                    "Door/(null)%LI10C40Q4M2E1B2S8",
                    "Door/SmallDoor%SI8C30Q4M2E1B2S6",
                    "AirtightHangarDoor/(null)%LS350C40Q40M16B2",
                    "AirtightSlideDoor/LargeBlockSlideDoor%LS20C40Q4M4E1B2A15",
                    "CubeBlock/ArmorCenter%LS140",
                    "CubeBlock/ArmorCorner%LS120",
                    "CubeBlock/ArmorInvCorner%LS135",
                    "CubeBlock/ArmorSide%LS130",
                    "CubeBlock/SmallArmorCenter%SS5",
                    "CubeBlock/SmallArmorCorner%SS5",
                    "CubeBlock/SmallArmorInvCorner%SS5",
                    "CubeBlock/SmallArmorSide%SS5",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Economy.sbc
                    "StoreBlock/StoreBlock%LS30C20M6E4B10",
                    "SafeZoneBlock/SafeZoneBlock%LS800C180H10V5L80B120",
                    "ContractBlock/ContractBlock%LS30C20M6E4B10",
                    "VendingMachine/VendingMachine%LI20C10M4E4B10",
                    "StoreBlock/AtmBlock%LS20C20M2B10E4",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Energy.sbc
                    "BatteryBlock/LargeBlockBatteryBlock%LS80C30N80B25",
                    "BatteryBlock/SmallBlockBatteryBlock%SS25C5N20B2",
                    "BatteryBlock/SmallBlockSmallBatteryBlock%SS4C2N2B2",
                    "Reactor/SmallBlockSmallGenerator%SS3C10L2J1P3M1B10",
                    "Reactor/SmallBlockLargeGenerator%SS60C9L9J3P95M5B25",
                    "Reactor/LargeBlockSmallGenerator%LS80C40L4J8P100M6B25",
                    "Reactor/LargeBlockLargeGenerator%LS1000C70L40J40T100P2000M20B75",
                    "HydrogenEngine/LargeHydrogenEngine%LS100C70J12Q20M12B4N1",
                    "HydrogenEngine/SmallHydrogenEngine%SS30C20J4Q6M4B1N1",
                    "WindTurbine/LargeBlockWindTurbine%LI40M8C20G24B2",
                    "SolarPanel/LargeBlockSolarPanel%LS4C14G12B4R32A4",
                    "SolarPanel/SmallBlockSolarPanel%SS2C2G4B1R8A1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Extras.sbc
                    "CubeBlock/Monolith%LS130T130",
                    "CubeBlock/Stereolith%LS130T130",
                    "CubeBlock/DeadAstronaut%SS13T13",
                    "CubeBlock/LargeDeadAstronaut%LS13T13",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Frostbite.sbc
                    "RadioAntenna/LargeBlockRadioAntennaDish%LC40G120S80B8O40",
                    "Door/LargeBlockGate%LS800C100Q100M20B10",
                    "Door/LargeBlockOffsetDoor%LS25C35Q4M4E1B2A6",
                    "CubeBlock/DeadBody01%LA1O1E1",
                    "CubeBlock/DeadBody02%LA1O1E1",
                    "CubeBlock/DeadBody03%LA1O1E1",
                    "CubeBlock/DeadBody04%LA1O1E1",
                    "CubeBlock/DeadBody05%LA1O1E1",
                    "CubeBlock/DeadBody06%LA1O1E1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Gravity.sbc
                    "GravityGenerator/(null)%LS150H6C60J4M6B40",
                    "GravityGeneratorSphere/(null)%LS150H6C60J4M6B40",
                    "VirtualMass/VirtualMassLarge%LS90T20C30B20H9",
                    "VirtualMass/VirtualMassSmall%SS3T2C2B2H1",
                    "SpaceBall/SpaceBallLarge%LS225C30B20H3",
                    "SpaceBall/SpaceBallSmall%SS70C10B7H1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Interiors.sbc
                    "Passage/(null)%LI74C20Q48",
                    "CubeBlock/Passage2%LI74C20Q48",
                    "CubeBlock/Passage2Wall%LI50C14Q32",
                    "CubeBlock/LargeStairs%LI50C30",
                    "CubeBlock/LargeRamp%LI70C16",
                    "CubeBlock/LargeSteelCatwalk%LI27C5Q20",
                    "CubeBlock/LargeSteelCatwalk2Sides%LI32C7Q25",
                    "CubeBlock/LargeSteelCatwalkCorner%LI32C7Q25",
                    "CubeBlock/LargeSteelCatwalkPlate%LI23C7Q17",
                    "CubeBlock/LargeCoverWall%LS4C10",
                    "CubeBlock/LargeCoverWallHalf%LS2C6",
                    "CubeBlock/LargeBlockInteriorWall%LI25C10",
                    "CubeBlock/LargeInteriorPillar%LI25C10Q4",
                    "Cockpit/PassengerSeatLarge%LI20C20",
                    "Cockpit/PassengerSeatSmall%SI20C20",
                    "Ladder2/(null)%LI10C20Q10",
                    "Ladder2/LadderSmall%SI10C20Q10",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_LCDPanels.sbc
                    "TextPanel/SmallTextPanel%SI1C4B4E3A1",
                    "TextPanel/SmallLCDPanelWide%SI1C8B8E6A2",
                    "TextPanel/SmallLCDPanel%SI1C4B4E3A2",
                    "TextPanel/LargeBlockCorner_LCD_1%LC5B3E1",
                    "TextPanel/LargeBlockCorner_LCD_2%LC5B3E1",
                    "TextPanel/LargeBlockCorner_LCD_Flat_1%LC5B3E1",
                    "TextPanel/LargeBlockCorner_LCD_Flat_2%LC5B3E1",
                    "TextPanel/SmallBlockCorner_LCD_1%SC3B2E1",
                    "TextPanel/SmallBlockCorner_LCD_2%SC3B2E1",
                    "TextPanel/SmallBlockCorner_LCD_Flat_1%SC3B2E1",
                    "TextPanel/SmallBlockCorner_LCD_Flat_2%SC3B2E1",
                    "TextPanel/LargeTextPanel%LI1C6B6E10A2",
                    "TextPanel/LargeLCDPanel%LI1C6B6E10A6",
                    "TextPanel/LargeLCDPanelWide%LI2C12B12E20A12",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Lights.sbc
                    "ReflectorLight/LargeBlockFrontLight%LS8J2I20C15A4",
                    "ReflectorLight/SmallBlockFrontLight%SS1J1I1C1A2",
                    "InteriorLight/SmallLight%LC2",
                    "InteriorLight/SmallBlockSmallLight%SC2",
                    "InteriorLight/LargeBlockLight_1corner%LC3",
                    "InteriorLight/LargeBlockLight_2corner%LC6",
                    "InteriorLight/SmallBlockLight_1corner%SC2",
                    "InteriorLight/SmallBlockLight_2corner%SC4",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Logistics.sbc
                    "OxygenTank/OxygenTankSmall%SS16J8Q10B8C10",
                    "OxygenTank/(null)%LS80J40Q60B8C40",
                    "OxygenTank/LargeHydrogenTank%LS280J80Q60B8C40",
                    "OxygenTank/LargeHydrogenTankSmall%LS80J40Q60B8C40",
                    "OxygenTank/SmallHydrogenTank%SS40J20Q30B4C20",
                    "OxygenTank/SmallHydrogenTankSmall%SS3J1Q2B4C2",
                    "AirVent/(null)%LS45C20M10B5",
                    "AirVent/SmallAirVent%SS8C10M2B5",
                    "CargoContainer/SmallBlockSmallContainer%SI3C1B1M1E1",
                    "CargoContainer/SmallBlockMediumContainer%SI30C10B4M4E1",
                    "CargoContainer/SmallBlockLargeContainer%SI75C25B6M8E1",
                    "CargoContainer/LargeBlockSmallContainer%LI40C40L4Q20M4E1B2",
                    "CargoContainer/LargeBlockLargeContainer%LI360C80L24Q60M20E1B8",
                    "Conveyor/SmallBlockConveyor%SI4C4M1",
                    "Conveyor/LargeBlockConveyor%LI20C30Q20M6",
                    "Collector/Collector%LS45C50Q12M8E4B10",
                    "Collector/CollectorSmall%SS35C35Q12M8E2B8",
                    "ShipConnector/Connector%LS150C40Q12M8B20",
                    "ShipConnector/ConnectorSmall%SS7C4Q2M1B4",
                    "ShipConnector/ConnectorMedium%SS21C12Q6M6B6",
                    "ConveyorConnector/ConveyorTube%LI14C20Q12M6",
                    "ConveyorConnector/ConveyorTubeSmall%SI1M1C1",
                    "ConveyorConnector/ConveyorTubeMedium%SI10C20Q10M6",
                    "ConveyorConnector/ConveyorFrameMedium%SI5C12Q5M2",
                    "ConveyorConnector/ConveyorTubeCurved%LI14C20Q12M6",
                    "ConveyorConnector/ConveyorTubeSmallCurved%SI1M1C1",
                    "ConveyorConnector/ConveyorTubeCurvedMedium%SI7C20Q10M6",
                    "Conveyor/SmallShipConveyorHub%SI25C45Q25M2",
                    "ConveyorSorter/LargeBlockConveyorSorter%LI50C120Q50B20M2",
                    "ConveyorSorter/MediumBlockConveyorSorter%SI5C12Q5B5M2",
                    "ConveyorSorter/SmallBlockConveyorSorter%SI5C12Q5B5M2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Mechanical.sbc
                    "PistonBase/LargePistonBase%LS15C10J4M4B2",
                    "ExtendedPistonBase/LargePistonBase%LS15C10J4M4B2",
                    "PistonTop/LargePistonTop%LS10J8",
                    "PistonBase/SmallPistonBase%SS4C4Q4M2B1",
                    "ExtendedPistonBase/SmallPistonBase%SS4C4Q4M2B1",
                    "PistonTop/SmallPistonTop%SS4J2",
                    "MotorStator/LargeStator%LS15C10J4M4B2",
                    "MotorRotor/LargeRotor%LS30J6",
                    "MotorStator/SmallStator%SS5C5Q1M1B1",
                    "MotorRotor/SmallRotor%SS12Q6",
                    "MotorAdvancedStator/LargeAdvancedStator%LS15C10J4M4B2",
                    "MotorAdvancedRotor/LargeAdvancedRotor%LS30J10",
                    "MotorAdvancedStator/SmallAdvancedStator%SS5C5Q1M1B1",
                    "MotorAdvancedRotor/SmallAdvancedRotor%SS30J10",
                    "MotorAdvancedStator/LargeHinge%LS16C10J4M4B2",
                    "MotorAdvancedRotor/LargeHingeHead%LS12J4C8",
                    "MotorAdvancedStator/MediumHinge%SS10C6J2M2B2",
                    "MotorAdvancedRotor/MediumHingeHead%SS6J2C4",
                    "MotorAdvancedStator/SmallHinge%SS6C4J1M2B2",
                    "MotorAdvancedRotor/SmallHingeHead%SS3J1C2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Medical.sbc
                    "MedicalRoom/LargeMedicalRoom%LI240C80L60Q20J5E10B10K15",
                    "CryoChamber/LargeBlockCryoChamber%LI40C20M8E8K3B30A10",
                    "CryoChamber/SmallBlockCryoChamber%SI20C10M4E4K3B15A5",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Production.sbc
                    "Refinery/LargeRefinery%LS1200C40J20M16L20B20",
                    "Refinery/Blast Furnace%LS120C20M10B10",
                    "OxygenGenerator/(null)%LS120C5J2M4B5",
                    "OxygenGenerator/OxygenGeneratorSmall%SS8C8J2M1B3",
                    "Assembler/LargeAssembler%LS140C80M20E10L10B160",
                    "Assembler/BasicAssembler%LS80C40M10E4B80",
                    "SurvivalKit/SurvivalKitLarge%LS30C2K3M4E1B5",
                    "SurvivalKit/SurvivalKit%SS6C2K3M4E1B5",
                    "OxygenFarm/LargeBlockOxygenFarm%LS40A100J20Q10C20B20",
                    "UpgradeModule/LargeProductivityModule%LS100C40Q20B60M4",
                    "UpgradeModule/LargeEffectivenessModule%LS100C50Q15T20M4",
                    "UpgradeModule/LargeEnergyModule%LS100C40Q20N20M4",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_ScrapRacePack.sbc
                    "ExhaustBlock/SmallExhaustPipe%SS2C1Q2M2",
                    "ExhaustBlock/LargeExhaustPipe%LS15C10J2M4",
                    "Cockpit/BuggyCockpit%SI30C25M2B20E4",
                    "CubeBlock/Viewport1%LS10C10A8",
                    "CubeBlock/Viewport2%LS10C10A8",
                    "MotorSuspension/OffroadSuspension3x3%LS25C15J6Q12M6",
                    "MotorSuspension/OffroadSuspension5x5%LS70C40J20Q30M20",
                    "MotorSuspension/OffroadSuspension1x1%LS25C15J6Q12M6",
                    "MotorSuspension/OffroadSmallSuspension3x3%SS8C7Q2M1",
                    "MotorSuspension/OffroadSmallSuspension5x5%SS16C12Q4M2",
                    "MotorSuspension/OffroadSmallSuspension1x1%SS8C7Q2M1",
                    "MotorSuspension/OffroadSuspension3x3mirrored%LS25C15J6Q12M6",
                    "MotorSuspension/OffroadSuspension5x5mirrored%LS70C40J20Q30M20",
                    "MotorSuspension/OffroadSuspension1x1mirrored%LS25C15J6Q12M6",
                    "MotorSuspension/OffroadSmallSuspension3x3mirrored%SS8C7Q2M1",
                    "MotorSuspension/OffroadSmallSuspension5x5mirrored%SS16C12Q4M2",
                    "MotorSuspension/OffroadSmallSuspension1x1mirrored%SS8C7Q2M1",
                    "Wheel/OffroadSmallRealWheel1x1%SS2C5J1",
                    "Wheel/OffroadSmallRealWheel%SS5C10J1",
                    "Wheel/OffroadSmallRealWheel5x5%SS7C15J2",
                    "Wheel/OffroadRealWheel1x1%LS8C20J4",
                    "Wheel/OffroadRealWheel%LS12C25J6",
                    "Wheel/OffroadRealWheel5x5%LS16C30J8",
                    "Wheel/OffroadSmallRealWheel1x1mirrored%SS2C5J1",
                    "Wheel/OffroadSmallRealWheelmirrored%SS5C10J1",
                    "Wheel/OffroadSmallRealWheel5x5mirrored%SS7C15J2",
                    "Wheel/OffroadRealWheel1x1mirrored%LS8C20J4",
                    "Wheel/OffroadRealWheelmirrored%LS12C25J6",
                    "Wheel/OffroadRealWheel5x5mirrored%LS16C30J8",
                    "Wheel/OffroadWheel1x1%LS8C20J4",
                    "Wheel/OffroadSmallWheel1x1%SS2C5J1",
                    "Wheel/OffroadWheel3x3%LS12C25J6",
                    "Wheel/OffroadSmallWheel3x3%SS5C10J1",
                    "Wheel/OffroadWheel5x5%LS16C30J8",
                    "Wheel/OffroadSmallWheel5x5%SS7C15J2",
                    "InteriorLight/OffsetLight%SC2",
                    "ReflectorLight/OffsetSpotlight%SC2A1",
                    "CubeBlock/BarredWindow%SG1C4",
                    "CubeBlock/BarredWindowSlope%SG1C4",
                    "CubeBlock/BarredWindowSide%SG1C4",
                    "CubeBlock/BarredWindowFace%SG1C4",
                    "CubeBlock/StorageShelf1%LG10S50C50Q50I50",
                    "CubeBlock/StorageShelf2%LG30N20M20L20",
                    "CubeBlock/StorageShelf3%LG10P10T10U10H2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_SparksOfTheFuturePack.sbc
                    "TextPanel/LargeLCDPanel5x5%LI25C150B25E250A150",
                    "TextPanel/LargeLCDPanel5x3%LI15C90B15E150A90",
                    "TextPanel/LargeLCDPanel3x3%LI10C50B10E90A50",
                    "CubeBlock/LargeBlockSciFiWall%LI25C10",
                    "EmissiveBlock/LargeNeonTubesStraight1%LI6Q6C2",
                    "EmissiveBlock/LargeNeonTubesStraight2%LI6Q6C2",
                    "EmissiveBlock/LargeNeonTubesCorner%LI6Q6C2",
                    "EmissiveBlock/LargeNeonTubesBendUp%LI12Q12C4",
                    "EmissiveBlock/LargeNeonTubesBendDown%LI3Q3C1",
                    "EmissiveBlock/LargeNeonTubesStraightEnd1%LI6Q6C2",
                    "EmissiveBlock/LargeNeonTubesStraightEnd2%LI10Q6C4",
                    "EmissiveBlock/LargeNeonTubesStraightDown%LI9Q9C3",
                    "EmissiveBlock/LargeNeonTubesU%LI18Q18C6",
                    "TerminalBlock/LargeBlockSciFiTerminal%LC4B2E4I2",
                    "ButtonPanel/LargeSciFiButtonTerminal%LI5C10B4E4",
                    "Door/SmallSideDoor%SI10C26A4M2E1B2S8",
                    "CubeBlock/LargeBlockBarCounter%LI16C10M1A6",
                    "CubeBlock/LargeBlockBarCounterCorner%LI24C14M2A10",
                    "ButtonPanel/LargeSciFiButtonPanel%LI10C20B20E5",
                    "Thrust/SmallBlockSmallThrustSciFi%SS2C2J1U1",
                    "Thrust/SmallBlockLargeThrustSciFi%SS5C2J5U12",
                    "Thrust/LargeBlockSmallThrustSciFi%LS25C60J8U80",
                    "Thrust/LargeBlockLargeThrustSciFi%LS150C100J40U960",
                    "Thrust/LargeBlockLargeAtmosphericThrustSciFi%LS230C60J50L40M1100",
                    "Thrust/LargeBlockSmallAtmosphericThrustSciFi%LS35C50J8L10M110",
                    "Thrust/SmallBlockLargeAtmosphericThrustSciFi%SS20C30J4L8M90",
                    "Thrust/SmallBlockSmallAtmosphericThrustSciFi%SS3C22J1L1M18",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Symbols.sbc
                    "CubeBlock/LargeSymbolA%LS4",
                    "CubeBlock/LargeSymbolB%LS4",
                    "CubeBlock/LargeSymbolC%LS4",
                    "CubeBlock/LargeSymbolD%LS4",
                    "CubeBlock/LargeSymbolE%LS4",
                    "CubeBlock/LargeSymbolF%LS4",
                    "CubeBlock/LargeSymbolG%LS4",
                    "CubeBlock/LargeSymbolH%LS4",
                    "CubeBlock/LargeSymbolI%LS4",
                    "CubeBlock/LargeSymbolJ%LS4",
                    "CubeBlock/LargeSymbolK%LS4",
                    "CubeBlock/LargeSymbolL%LS4",
                    "CubeBlock/LargeSymbolM%LS4",
                    "CubeBlock/LargeSymbolN%LS4",
                    "CubeBlock/LargeSymbolO%LS4",
                    "CubeBlock/LargeSymbolP%LS4",
                    "CubeBlock/LargeSymbolQ%LS4",
                    "CubeBlock/LargeSymbolR%LS4",
                    "CubeBlock/LargeSymbolS%LS4",
                    "CubeBlock/LargeSymbolT%LS4",
                    "CubeBlock/LargeSymbolU%LS4",
                    "CubeBlock/LargeSymbolV%LS4",
                    "CubeBlock/LargeSymbolW%LS4",
                    "CubeBlock/LargeSymbolX%LS4",
                    "CubeBlock/LargeSymbolY%LS4",
                    "CubeBlock/LargeSymbolZ%LS4",
                    "CubeBlock/SmallSymbolA%SS1",
                    "CubeBlock/SmallSymbolB%SS1",
                    "CubeBlock/SmallSymbolC%SS1",
                    "CubeBlock/SmallSymbolD%SS1",
                    "CubeBlock/SmallSymbolE%SS1",
                    "CubeBlock/SmallSymbolF%SS1",
                    "CubeBlock/SmallSymbolG%SS1",
                    "CubeBlock/SmallSymbolH%SS1",
                    "CubeBlock/SmallSymbolI%SS1",
                    "CubeBlock/SmallSymbolJ%SS1",
                    "CubeBlock/SmallSymbolK%SS1",
                    "CubeBlock/SmallSymbolL%SS1",
                    "CubeBlock/SmallSymbolM%SS1",
                    "CubeBlock/SmallSymbolN%SS1",
                    "CubeBlock/SmallSymbolO%SS1",
                    "CubeBlock/SmallSymbolP%SS1",
                    "CubeBlock/SmallSymbolQ%SS1",
                    "CubeBlock/SmallSymbolR%SS1",
                    "CubeBlock/SmallSymbolS%SS1",
                    "CubeBlock/SmallSymbolT%SS1",
                    "CubeBlock/SmallSymbolU%SS1",
                    "CubeBlock/SmallSymbolV%SS1",
                    "CubeBlock/SmallSymbolW%SS1",
                    "CubeBlock/SmallSymbolX%SS1",
                    "CubeBlock/SmallSymbolY%SS1",
                    "CubeBlock/SmallSymbolZ%SS1",
                    "CubeBlock/LargeSymbol0%LS4",
                    "CubeBlock/LargeSymbol1%LS4",
                    "CubeBlock/LargeSymbol2%LS4",
                    "CubeBlock/LargeSymbol3%LS4",
                    "CubeBlock/LargeSymbol4%LS4",
                    "CubeBlock/LargeSymbol5%LS4",
                    "CubeBlock/LargeSymbol6%LS4",
                    "CubeBlock/LargeSymbol7%LS4",
                    "CubeBlock/LargeSymbol8%LS4",
                    "CubeBlock/LargeSymbol9%LS4",
                    "CubeBlock/SmallSymbol0%SS1",
                    "CubeBlock/SmallSymbol1%SS1",
                    "CubeBlock/SmallSymbol2%SS1",
                    "CubeBlock/SmallSymbol3%SS1",
                    "CubeBlock/SmallSymbol4%SS1",
                    "CubeBlock/SmallSymbol5%SS1",
                    "CubeBlock/SmallSymbol6%SS1",
                    "CubeBlock/SmallSymbol7%SS1",
                    "CubeBlock/SmallSymbol8%SS1",
                    "CubeBlock/SmallSymbol9%SS1",
                    "CubeBlock/LargeSymbolHyphen%LS4",
                    "CubeBlock/LargeSymbolUnderscore%LS4",
                    "CubeBlock/LargeSymbolDot%LS4",
                    "CubeBlock/LargeSymbolApostrophe%LS4",
                    "CubeBlock/LargeSymbolAnd%LS4",
                    "CubeBlock/LargeSymbolColon%LS4",
                    "CubeBlock/LargeSymbolExclamationMark%LS4",
                    "CubeBlock/LargeSymbolQuestionMark%LS4",
                    "CubeBlock/SmallSymbolHyphen%SS1",
                    "CubeBlock/SmallSymbolUnderscore%SS1",
                    "CubeBlock/SmallSymbolDot%SS1",
                    "CubeBlock/SmallSymbolApostrophe%SS1",
                    "CubeBlock/SmallSymbolAnd%SS1",
                    "CubeBlock/SmallSymbolColon%SS1",
                    "CubeBlock/SmallSymbolExclamationMark%SS1",
                    "CubeBlock/SmallSymbolQuestionMark%SS1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Thrusters.sbc
                    "Thrust/SmallBlockSmallThrust%SS2C2J1U1",
                    "Thrust/SmallBlockLargeThrust%SS5C2J5U12",
                    "Thrust/LargeBlockSmallThrust%LS25C60J8U80",
                    "Thrust/LargeBlockLargeThrust%LS150C100J40U960",
                    "Thrust/LargeBlockLargeHydrogenThrust%LS150C180L250J40",
                    "Thrust/LargeBlockSmallHydrogenThrust%LS25C60L40J8",
                    "Thrust/SmallBlockLargeHydrogenThrust%SS30C30L22J10",
                    "Thrust/SmallBlockSmallHydrogenThrust%SS7C15L4J2",
                    "Thrust/LargeBlockLargeAtmosphericThrust%LS230C60J50L40M1100",
                    "Thrust/LargeBlockSmallAtmosphericThrust%LS35C50J8L10M110",
                    "Thrust/SmallBlockLargeAtmosphericThrust%SS20C30J4L8M90",
                    "Thrust/SmallBlockSmallAtmosphericThrust%SS3C22J1L1M18",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Tools.sbc
                    "Drill/SmallBlockDrill%SS32C30J4M1B1",
                    "Drill/LargeBlockDrill%LS300C40J12M5B5",
                    "ShipGrinder/LargeShipGrinder%LS20C30J1M4B2",
                    "ShipGrinder/SmallShipGrinder%SS12C17Q4M4B2",
                    "ShipWelder/LargeShipWelder%LS20C30J1M2B2",
                    "ShipWelder/SmallShipWelder%SS12C17Q6M2B2",
                    "OreDetector/LargeOreDetector%LS50C40M5B25D20",
                    "OreDetector/SmallBlockOreDetector%SS3C2M1B1D1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Utility.sbc
                    "LandingGear/LargeBlockLandingGear%LS150C20M6",
                    "LandingGear/SmallBlockLandingGear%SS2C5M1",
                    "JumpDrive/LargeJumpDrive%LS60L50H20D20N120T1000B300C40",
                    "CameraBlock/SmallCameraBlock%SS2B3",
                    "CameraBlock/LargeCameraBlock%LS2B3",
                    "MergeBlock/LargeShipMergeBlock%LS12C15M2J6B2",
                    "MergeBlock/SmallShipMergeBlock%SS4C5M1Q2B1",
                    "Parachute/LgParachute%LS9C25Q5M3B2",
                    "Parachute/SmParachute%SS2C2Q1M1B1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Warfare1.sbc
                    "CargoContainer/LargeBlockWeaponRack%LI30C20",
                    "CargoContainer/SmallBlockWeaponRack%SI3C3",
                    "CubeBlock/FireCover%LS4C10",
                    "CubeBlock/FireCoverCorner%LS8C20",
                    "CubeBlock/HalfWindow%LG4S10A10",
                    "CubeBlock/HalfWindowInv%LG4S10A10",
                    "CubeBlock/HalfWindowCorner%LG8S20A20",
                    "CubeBlock/HalfWindowCornerInv%LG8S20A20",
                    "CubeBlock/Embrasure%LS30C20L10",
                    "CubeBlock/PassageSciFi%LI74C20Q48",
                    "CubeBlock/PassageSciFiWall%LI50C14Q32",
                    "CubeBlock/PassageSciFiIntersection%LI35C10Q25",
                    "CubeBlock/PassageSciFiGate%LI35C10Q25",
                    "InteriorLight/PassageSciFiLight%LI74C20Q48",
                    "CubeBlock/PassageScifiCorner%LI74C20Q48",
                    "CubeBlock/PassageSciFiTjunction%LI55C16Q38",
                    "CubeBlock/PassageSciFiWindow%LI60C16A16Q38",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Weapons.sbc
                    "Warhead/LargeWarhead%LS20G24C12Q12B2F6",
                    "Warhead/SmallWarhead%SS4G1C1Q2B1F2",
                    "Decoy/LargeDecoy%LS30C10B10O1J2",
                    "Decoy/SmallDecoy%SS2C1B1O1Q2",
                    "LargeGatlingTurret/(null)%LS20C30L15Q6M8B10",
                    "LargeGatlingTurret/SmallGatlingTurret%SS10C30L5Q6M4B10",
                    "LargeMissileTurret/(null)%LS20C40L5J6M16B12",
                    "LargeMissileTurret/SmallMissileTurret%SS10C40L2J2M8B12",
                    "InteriorTurret/LargeInteriorTurret%LI6C20Q1M2B5S4",
                    "SmallMissileLauncher/(null)%SS4C2L1J4M1B1",
                    "SmallMissileLauncher/LargeMissileLauncher%LS35C8L30J25M6B4",
                    "SmallMissileLauncherReload/SmallRocketLauncherReload%SQ50I50C24J8L10M4B2S8",
                    "SmallGatlingGun/(null)%SS4C1L2Q6M1B1",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Wheels.sbc
                    "MotorSuspension/Suspension3x3%LS25C15J6Q12M6",
                    "MotorSuspension/Suspension5x5%LS70C40J20Q30M20",
                    "MotorSuspension/Suspension1x1%LS25C15J6Q12M6",
                    "MotorSuspension/SmallSuspension3x3%SS8C7Q2M1",
                    "MotorSuspension/SmallSuspension5x5%SS16C12Q4M2",
                    "MotorSuspension/SmallSuspension1x1%SS8C7Q2M1",
                    "MotorSuspension/Suspension3x3mirrored%LS25C15J6Q12M6",
                    "MotorSuspension/Suspension5x5mirrored%LS70C40J20Q30M20",
                    "MotorSuspension/Suspension1x1mirrored%LS25C15J6Q12M6",
                    "MotorSuspension/SmallSuspension3x3mirrored%SS8C7Q2M1",
                    "MotorSuspension/SmallSuspension5x5mirrored%SS16C12Q4M2",
                    "MotorSuspension/SmallSuspension1x1mirrored%SS8C7Q2M1",
                    "Wheel/SmallRealWheel1x1%SS2C5J1",
                    "Wheel/SmallRealWheel%SS5C10J1",
                    "Wheel/SmallRealWheel5x5%SS7C15J2",
                    "Wheel/RealWheel1x1%LS8C20J4",
                    "Wheel/RealWheel%LS12C25J6",
                    "Wheel/RealWheel5x5%LS16C30J8",
                    "Wheel/SmallRealWheel1x1mirrored%SS2C5J1",
                    "Wheel/SmallRealWheelmirrored%SS5C10J1",
                    "Wheel/SmallRealWheel5x5mirrored%SS7C15J2",
                    "Wheel/RealWheel1x1mirrored%LS8C20J4",
                    "Wheel/RealWheelmirrored%LS12C25J6",
                    "Wheel/RealWheel5x5mirrored%LS16C30J8",
                    "Wheel/Wheel1x1%LS8C20J4",
                    "Wheel/SmallWheel1x1%SS2C5J1",
                    "Wheel/Wheel3x3%LS12C25J6",
                    "Wheel/SmallWheel3x3%SS5C10J1",
                    "Wheel/Wheel5x5%LS16C30J8",
                    "Wheel/SmallWheel5x5%SS7C15J2",
                    // C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks\CubeBlocks_Windows.sbc
                    "CubeBlock/LargeWindowSquare%LI12C8Q4",
                    "CubeBlock/LargeWindowEdge%LI16C12Q6",
                    "CubeBlock/Window1x2Slope%LG16A55",
                    "CubeBlock/Window1x2Inv%LG15A40",
                    "CubeBlock/Window1x2Face%LG15A40",
                    "CubeBlock/Window1x2SideLeft%LG13A26",
                    "CubeBlock/Window1x2SideLeftInv%LG13A26",
                    "CubeBlock/Window1x2SideRight%LG13A26",
                    "CubeBlock/Window1x2SideRightInv%LG13A26",
                    "CubeBlock/Window1x1Slope%LG12A35",
                    "CubeBlock/Window1x1Face%LG11A24",
                    "CubeBlock/Window1x1Side%LG9A17",
                    "CubeBlock/Window1x1SideInv%LG9A17",
                    "CubeBlock/Window1x1Inv%LG11A24",
                    "CubeBlock/Window1x2Flat%LG15A50",
                    "CubeBlock/Window1x2FlatInv%LG15A50",
                    "CubeBlock/Window1x1Flat%LG10A25",
                    "CubeBlock/Window1x1FlatInv%LG10A25",
                    "CubeBlock/Window3x3Flat%LG40A196",
                    "CubeBlock/Window3x3FlatInv%LG40A196",
                    "CubeBlock/Window2x3Flat%LG25A140",
                    "CubeBlock/Window2x3FlatInv%LG25A140",
                    "CubeBlock/SmallWindow1x2Slope%SG1A3",
                    "CubeBlock/SmallWindow1x2Inv%SG1A3",
                    "CubeBlock/SmallWindow1x2Face%SG1A3",
                    "CubeBlock/SmallWindow1x2SideLeft%SG1A3",
                    "CubeBlock/SmallWindow1x2SideLeftInv%SG1A3",
                    "CubeBlock/SmallWindow1x2SideRight%SG1A3",
                    "CubeBlock/SmallWindow1x2SideRightInv%SG1A3",
                    "CubeBlock/SmallWindow1x1Slope%SG1A2",
                    "CubeBlock/SmallWindow1x1Face%SG1A2",
                    "CubeBlock/SmallWindow1x1Side%SG1A2",
                    "CubeBlock/SmallWindow1x1SideInv%SG1A2",
                    "CubeBlock/SmallWindow1x1Inv%SG1A2",
                    "CubeBlock/SmallWindow1x2Flat%SG1A3",
                    "CubeBlock/SmallWindow1x2FlatInv%SG1A3",
                    "CubeBlock/SmallWindow1x1Flat%SG1A2",
                    "CubeBlock/SmallWindow1x1FlatInv%SG1A2",
                    "CubeBlock/SmallWindow3x3Flat%SG3A12",
                    "CubeBlock/SmallWindow3x3FlatInv%SG3A12",
                    "CubeBlock/SmallWindow2x3Flat%SG2A8",
                    "CubeBlock/SmallWindow2x3FlatInv%SG2A8",
                    // C:\Program Files (x86)\Steam\steamapps\workshop\content\244850\429053416\Data\CubeBlocks.sbc
                    "LargeGatlingTurret/OKIObserverSM%SS20C20L5Q1M12D1B6",
                    "LargeGatlingTurret/OKIDesignator%LS40C55L12Q5M12D6B24",
                    "SmallGatlingGun/OKI23mmDGfixed%SS5C2Q3M1B1",
                    "SmallGatlingGun/OKI50mmSGfixed%SS6C2Q6J1M1B1",
                    "SmallMissileLauncher/OKI122mmAGfixed%SS20C25L8Q2J8M10B5",
                    "LargeGatlingTurret/OKI23mmSG%SS10C25L2Q8M8B12",
                    "LargeGatlingTurret/OKI50mmSG%SS15C30L2Q12J1M4B18",
                    "LargeGatlingTurret/OKI14mmVT%SS105C50L30Q8M12B10",
                    "LargeGatlingTurret/OKI50mmVT%SS125C50L37Q8J2M6B10",
                    "LargeGatlingTurret/OKI122mmVT%SS125C50L40J8M6B10",
                    "LargeMissileTurret/OKIMLVT%SS125C55L30J6M16B12",
                    "SmallGatlingGun/OKI50mmFGAT%LS160C80L10Q48J6M45B18",
                    "SmallMissileLauncher/OKI230mmBCfixed%LS120C40L8Q12J40M18B10",
                    "SmallMissileLauncher/OKI180mmHVXfixed%LS260C220L80Q30J60M20T120N240B30",
                    "SmallMissileLauncher/OKI75mmHVPfixed%LS260C220L80Q30J60M20T120N240B30",
                    "LargeGatlingTurret/OKI76mmBSD%LS20C50L4Q2J8M24B10",
                    "LargeGatlingTurret/OKI230mmBCBRD%LS160C60L12Q12J40M60B12",
                    "LargeGatlingTurret/OKI23mmDG%LS20C30L5Q8M12B10",
                    "LargeGatlingTurret/OKI50mmAG%LS50C35L12Q8J2M6B10",
                    "LargeGatlingTurret/OKI76mmAG%LS50C35L15J8M6B10",
                    "LargeGatlingTurret/OKI50mmGat%LS240C120L24Q48J6M90B24",
                    "LargeMissileTurret/OKIHvyMissileTurret%LS240C140L36Q24J40M40B48",
                    "LargeGatlingTurret/OKI230mmBC%LS240C120L24Q12J40M42B18",
                    "LargeGatlingTurret/OKI230mmBAT%LS800C240L72Q36J120M120B36",
                };
                foreach(string miniString in initializer)
                {
                    BlockType blockType = FromMiniString(miniString, dialect);
                    if (blockType.Size == MyCubeSize.Large)
                    {
                        largeSize[blockType.Label] = blockType;
                    } else
                    {
                        smallSize[blockType.Label] = blockType;
                    }
                }
            }

            public static BlockType GetBlockType(string blueprintId, MyCubeSize cubeSize = MyCubeSize.Large)
            {
                switch(cubeSize)
                {
                    case MyCubeSize.Large:
                        return largeSize.GetValueOrDefault(blueprintId, null);
                    case MyCubeSize.Small:
                        return smallSize.GetValueOrDefault(blueprintId, null);
                }
                return null;
            }

            


            public static BlockType FromMiniString(string miniString, Dictionary<char, Component.ComponentType> dialect)
            {
                string[] parts = miniString.Split('%');
                string label = "MyObjectBuilder_" + parts[0];
                MyCubeSize size = parts[1].StartsWith("L") ? MyCubeSize.Large : MyCubeSize.Small;
                Dictionary<Component.ComponentType, int> componentCount = new Dictionary<Component.ComponentType, int>();
                Component.ComponentType current = Component.ComponentType.BulletproofGlass;
                int count = 0;
                for (int i = 1; i < parts[1].Length; ++i)
                {
                    char c = parts[1][i];
                    bool isNumber = c >= '0' && c <= '9';
                    if (!isNumber)
                    {
                        componentCount[current] = count;
                        count = 0;
                        current = dialect[c];
                    } else
                    {
                        count = count * 10 + (c - '0');
                    }
                }
                componentCount[current] = count;

                return new BlockType(label, size, componentCount);
            }
        }
    }
}
